version: "3.9"
services:
  db:
    image: postgres:16
    container_name: moveo-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moveo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d moveo"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
