[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["cd server && npm install --production=false"]

[phases.build]
cmds = ["cd server && npx prisma generate && npm run build && npx prisma migrate deploy"]

[start]
cmd = "cd server && npm start"
